name: EAS Web Deploy
on: push

jobs:
  deploy-web:
    name: EAS Web Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: bun install
        working-directory: ./bitmeme

      - name: Export web build
        run: npx expo export -p web
        working-directory: ./bitmeme

      - name: Deploy to production
        run: bun run eas deploy --prod
        working-directory: ./bitmeme